# Generated by Django 5.0.7 on 2024-07-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(max_length=1000),
        ),
    ]
